In [5]:
#sets in python
#set can have different datatype in it
#set constructor
#python collections(arrays)
#in keyword in set
#use add() to add element
thisset={"banana","apple","cherry"}
print("banana" in thisset)
thisset={"banana","apple","cherry"}
print("banana" not in thisset)
thisset.add("orange")
print(thisset)

True
False
{'apple', 'banana', 'cherry', 'orange'}


In [18]:
#to add two sets(tuple,list,dictionary se bhi update krskte h using update to sets)
thisset={"banana","apple","cherry"}
tropical={"xyz","mohit","nilanshu"}

thisset.update(tropical)
print(thisset)
mylist=["kiwi","orange"]
thisset.update(mylist)
print(thisset)
#remove item using remove
thisset.remove("banana")
print(thisset)
thisset.discard("orange")
print(thisset)
thisset.discard("banana")
print(thisset)
#we can also use pop() 
x=thisset.pop()
print(thisset)
#clear to delete the complete set
#can also use del keyword like del thisset
thisset.clear() 
print(thisset)


{'apple', 'xyz', 'nilanshu', 'banana', 'mohit', 'cherry'}
{'apple', 'xyz', 'nilanshu', 'banana', 'mohit', 'orange', 'cherry', 'kiwi'}
{'apple', 'xyz', 'nilanshu', 'mohit', 'orange', 'cherry', 'kiwi'}
{'apple', 'xyz', 'nilanshu', 'mohit', 'cherry', 'kiwi'}
{'apple', 'xyz', 'nilanshu', 'mohit', 'cherry', 'kiwi'}
{'xyz', 'nilanshu', 'mohit', 'cherry', 'kiwi'}
set()


In [19]:
#loop items in the set
thisset={"banana","apple","cherry"}
for x in thisset:
    print(x)

apple
banana
cherry


In [20]:
#join sets by union() and update()
#the intersection() keeps only the duplicates
#the difference() keeps the items from one set that are not in set b
set1={'a','b','c'}
set2={1,2,3}
set3=set1.union(set2)
print(set3)

{1, 2, 3, 'b', 'c', 'a'}


In [21]:
#this is also use | instead of writing union()(can be used to join only set with set)
set1={'a','b','c'}
set2={1,2,3}
set3=set1|set2
print(set3)

{1, 2, 3, 'b', 'c', 'a'}


In [22]:
#join multiple sets
set1={'a','b','c'}
set2={1,2,3}
set3={'john','elena'}
set4= set1|set2|set3
print(set4)

{1, 2, 3, 'elena', 'b', 'c', 'a', 'john'}


In [23]:
#join a set and a tuple to take result as set
set1={'a','b','c'}
y=(1,2,3)
z=set1.union(y)
print(z)

{1, 2, 3, 'b', 'c', 'a'}


In [24]:
#update() inserts items of set2 into set1
set1={'a','b','c'}
set2={1,2,3}
set1.update(set2)
print(set1)
#both union() and update() will exclude any duplicate values

{1, 2, 3, 'b', 'c', 'a'}


In [26]:
#intersection
set1={'a','b','c',1}
set2={1,2,3}
set3=set1&set2
print(set3)

{1}


In [29]:
set1={'a','b','c',1}
set2={1,2,3}
set1.intersection_update(set2)
print(set1)

{1}


In [38]:
set1={'apple',1,'banana',0,'cherry'}
set2={False,'google',1,'apple',2,True}
set3=set1.intersection(set2)
print(set3)

{False, 1, 'apple'}


In [37]:
#difference
set1={'a','b','c',1}
set2={1,2,3}
set3=set1-set2
print(set3)

{'b', 'c', 'a'}


In [40]:
#difference_update
set1={'a','b','c',1}
set2={1,2,3}
set1.difference_update(set2)
print(set1)

{'b', 'c', 'a'}


In [41]:
#symmetric difference----keeps items that are not present in both sets
set1={'a','b','c',1}
set2={1,2,3}
set3=set1.symmetric_difference(set2)
print(set3)

{2, 3, 'b', 'c', 'a'}


In [42]:
#issuperset to check superset
#issubset to check if subset or not
#existence check
#get the unique elements of a list
#set of sets
#set operations using methods and builtins
#a.issubset(a)tests whether each element of c is in a
#a.issuperset(c)tests whether each element of c is in a
#subset(a<=b)
#superset(a>=b)


In [64]:
#WAP that creates two sets squares and cubes in range 1 to 10,demonstrate the use of update,add,clear,remove,pop

squares = {x**2 for x in range(1, 11)}
cubes = {x**3 for x in range(1, 11)}

print("Initial squares set:", squares)
print("Initial cubes set:", cubes)

squares.update(cubes)
print(squares)

squares.add('Shashank')
print(squares)

cubes.clear()
print(cubes)

squares.remove(64)
print(squares)

a = squares.pop()
print(a)
print(squares)

Initial squares set: {64, 1, 4, 36, 100, 9, 16, 49, 81, 25}
Initial cubes set: {64, 1, 512, 8, 1000, 343, 216, 729, 27, 125}
{64, 1, 512, 4, 8, 9, 16, 81, 343, 216, 25, 729, 27, 36, 100, 1000, 49, 125}
{64, 1, 512, 4, 8, 9, 16, 81, 'Shashank', 343, 216, 25, 729, 27, 36, 100, 1000, 49, 125}
set()
{1, 512, 4, 8, 9, 16, 81, 'Shashank', 343, 216, 25, 729, 27, 36, 100, 1000, 49, 125}
1
{512, 4, 8, 9, 16, 81, 'Shashank', 343, 216, 25, 729, 27, 36, 100, 1000, 49, 125}


In [68]:
#wap that creates two sets 1 of even numbers in the range 1 to 10 and the other has all composite number in the range 1 to 20,demonstrate the use of all function issuperset ,len() and sum function on the set
a={x for x in range(1,11) if x%2==0}
print(a)
b={x for x in range(1,21) if any(x%i==0 for i in range(2,x))}
print(b)
all_composite=

{2, 4, 6, 8, 10}
{4, 6, 8, 9, 10, 12, 14, 15, 16, 18, 20}


In [74]:
#Numpy
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [77]:
#dimesnion in arrays
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3,],[4,5,6]]])
print(arr)
#to check number of dimension in array
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
#access array elements
